name: Greetings

on: [pull_request_target, issues]

jobs:
  windows-env:
    runs-on: windows-latest
    env:
      PKG_CONFIG: ${{ env.VCPKG_ROOT }}/packages
    steps:
    - uses: actions/checkout@v3
    - name: echo
      run: echo "${env:PKG_CONFIG}"
